version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - D:\Apps\postgres_data:/var/lib/postgresql/data  # Volume giữ dữ liệu
#volumes:
#  postgres_data:
